services:
  # база данных
  db:
    container_name: wallet_db
    image: postgres:16          
    environment:                # переменные окружения
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: wallet
    ports:
      - "5433:5432"             # хост:контейнер
    volumes:
      - pg_data_wallet:/var/lib/postgresql  # сохраняем данные

    # Проверка здоровья (ждём, пока БД реально запустится)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s      # Проверять каждые 3 секунд
      timeout: 12s       # Таймаут проверки
      retries: 4        # Количество попыток

  # тестовая база данных
  test_db:
    container_name: wallet_test_db
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test_db
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d test_db"]
      interval: 3s
      timeout: 12s
      retries: 4

  # приложение
  app:
    container_name: app_wallet
    build: .                    # собрать образ из текущей папки (Dockerfile)
    ports:
      - "8000:8000"
    depends_on:                 # ждём запуска бд
        db:
          condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:admin@wallet_db:5432/wallet
    working_dir: /app

  # UI
  frontend:
    container_name: wallet_frontend
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - app

# Том
volumes:
  pg_data_wallet: