# Список сервисов (контейнеров)
services:
  # Первый сервис: база данных
  db:
    container_name: wallet_db
    restart: unless-stopped
    image: postgres:16          # готовый образ из Docker Hub
    environment:                # переменные окружения
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: wallet
    ports:
      - "5433:5432"             # второй порт не трогать
    volumes:
      - pg_data_wallet:/var/lib/postgresql/data

    # Проверка здоровья (ждём, пока БД реально запустится)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s      # Проверять каждые 3 секунд
      timeout: 12s       # Таймаут проверки
      retries: 4        # Количество попыток

  test_db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test_db
    ports:
      - "5434:5432"  # ← другой порт

  # Второй сервис: твоё приложение
  app:
    container_name: app_wallet
    restart: unless-stopped
    build: .                    # собирать образ из текущей папки (Dockerfile)
    ports:
      - "8000:8000" # второй порт не трогать
    depends_on:                 # ждём, пока db запустится
        db:
          condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:admin@wallet_db:5432/wallet
    working_dir: /app
    env_file:
      - .env

  bot:
    build: .
    container_name: wallet_bot
    restart: unless-stopped
    command: python -m bot.main
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    container_name: wallet_frontend
    restart: unless-stopped
    image: nginx:alpine
    ports:
      - "8080:80" # второй порт не трогать
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - app

# Тома (хранилища данных)
volumes:
  pg_data_wallet: